### ISSUE TITLE
Publish contribution guidelines to help newcomers with their first contributions (code standards, etc.)

### ISSUE THREAD

**Issue by wmalgadey** [wmalgadey/PyTado#104]
- added black linter to workflows
- added templates for PR and issues 
- [x] make clear, that the API we use is not documented/open, and that all bugfixes will need  a proper test and explanation

**Comment by wmalgadey** [comment]
@palazzem what guidelines should we add? I think the templates and black linter are a good start, what do you think?

**Comment by palazzem** [comment]
I've generalized some contributing guidelines in this file: https://github.com/palazzem/ha-econnect-alarm/blob/main/CONTRIBUTING.md

I think we can start small, and then grow as soon as the community contributes back!

**Comment by palazzem** [comment]
Minor thing to consider as you added already coverage reporting (that is great!). What if we use a third-party tool that can provide easier visualization of your coverage? This is an example where you can navigate for each PR showing which lines are covered and which not: https://coveralls.io/github/palazzem/ha-econnect-alarm?branch=main

Again this is minor, we can keep this in our backlog and re-evaluate in the future if you prefer to stay with current coverage tools.

**Comment by wmalgadey** [comment]
@palazzem the coverage tool I use generates a nice report, which could be used for github pages. I never used github pages before, so it will take some time to create it :D

**Comment by palazzem** [comment]
I'm continuing to write here as we can use this issue as a way to brainstorm ideas around "guidelines". `PyTado` is a beast project as you are going to support an incredible amount of devices, with the challenge of Tado not providing a clear OpenAPI specification (so things may break without us knowing). One guidelines and best practices to include in our contribution guidelines is that each time something breaks, code will be merged only if there is a clear description of the issue / model is experiencing the problem, with a test that explicitly say it is a regression test ([example](https://github.com/palazzem/ha-econnect-alarm/blob/main/tests/test_devices.py#L600-L602)).

The overall goal, is that we contributors with our help, defines a test to cover their case and we include a reference in our code to remember "if this test breaks, all these devices will stop working". What do you think?

**Comment by palazzem** [comment]
> @palazzem the coverage tool I use generates a nice report, which could be used for github pages. I never used github pages before, so it will take some time to create it :D

This is great then! a new thing to learn!

**Comment by wmalgadey** [comment]
Will close this issue! Contribution was added and Readme has changed a lot.
