### ISSUE TITLE
Add mypy to pre-commit hooks

### ISSUE THREAD

**Issue by wmalgadey** [wmalgadey/PyTado#113]
> Eventually (but with the real meaning of "eventually in the far future"), we may want to activate `mypy` at its full strict mode to have "typed" code. We can't do it right now as it will be overwhelming do all the required changes, but it's something to take in consideration for the future!

_Originally posted by @palazzem in https://github.com/wmalgadey/PyTado/pull/110#discussion_r1893908739_

**Comment by wmalgadey** [comment]
@palazzem and @erwindouna as far as I understand, what we did up to now, we already added mypi in pre commit configuration. And I did fix all current errors related to pre-commit reports in #121

**Comment by erwindouna** [comment]
It's in. And operational!

**Comment by wmalgadey** [comment]
Ok, let's close this issue. I sure don't know, what all those pre commit hooks do 😁 but we have some of them now. Let's close this issue, so we can move forward, if we have too much configure here, we can change this asap!
