### ISSUE TITLE
The pypi released 0.2.8 release not the one with 0.2.8 tag

### ISSUE THREAD

**Issue by awarecan** [wmalgadey/PyTado#13]
I downloaded files from [PyPi](https://pypi.org/project/python-tado/#files), as you can see the URL is not changed
![image](https://user-images.githubusercontent.com/7366491/54724514-b80ac780-4b28-11e9-90b7-6bcb696b5d6b.png)

**Comment by bhaap** [comment]
This repo does not maintain PyTado. This fork has the name Python-tado on pypi
https://pypi.org/project/python-tado/

**Comment by awarecan** [comment]
Please check my link, I download the files from https://pypi.org/project/python-tado/#files

**Comment by wmalgadey** [comment]
ok, I will check. I will use twine again!

**Comment by wmalgadey** [comment]
sorry @all, I did a mistake here on my local repository. Sadly I had to pump the version to 0.2.9.
