### ISSUE TITLE
[Feature]: read current supply temperature 

### ISSUE THREAD

**Issue by LarsStegman** [wmalgadey/PyTado#131]
## Describe the Feature
The website https://model-selector.tado.com/ shows the current supply temperature and supports setting the max supply temperature. It would be nice to also do this through this library. 

![image](https://github.com/user-attachments/assets/a86b0803-fae6-4274-9b39-c1fd66c8ec33)

---

## Why Is This Feature Useful?
Useful for debugging and optimising the system. 

---

## Proposed Solution
If you have a suggestion for how to implement the feature, provide details here.

no idea if this is possible through an API. 

---

## Alternatives Considered
List any alternative approaches or features you considered and why they might not work as well.

---

## Additional Context
Add any other context, screenshots, or examples that help explain your request.

---

### Checklist
- [x] I have searched the existing issues and discussions to ensure this is not a duplicate.
- [x] I have provided a clear and concise description of my feature request.
- [x] I have included any relevant examples or details to support my proposal.

Thank you for helping to improve PyTado! 🚀

**Comment by wmalgadey** [comment]
That seems to only work for pre Tado X devices, because I do not have an `auth code`. So I am not able to test ist.

**Comment by wmalgadey** [comment]
@LarsStegman, yes the information unter "network" would be helpful, so we can add the needed endpoints and create tests to ensure everything is working.

**Comment by LarsStegman** [comment]
Hi, I have exported this har file (and removed my credentials :P)

[model-selector.tado.com.har.json](https://github.com/user-attachments/files/18265858/model-selector.tado.com.har.json)

**Comment by wmalgadey** [comment]
@LarsStegman take a look into #134 please. I added two methods in the same fashion we did bevor. Because the current and the max output are two calls, I added two methods.

I will merge this later, if it suites your need?

**Comment by wmalgadey** [comment]
I can't test the implementation, because I get a 404 if I pass my Tado X bridge ID to those endpoints. This could have two reasons:

1. the tado x bridge doesn't support boilers?
2. I do not have a boiler installed!

**Comment by LarsStegman** [comment]
> @LarsStegman take a look into #134 please. I added two methods in the same fashion we did bevor. Because the current and the max output are two calls, I added two methods.
> 
> I will merge this later, if it suites your need?

I tested it and reading the values works. Is it also possible to add writing the max temperature?

**Comment by wmalgadey** [comment]
done!
