### ISSUE TITLE
Add timeout to HTTP calls

### ISSUE THREAD

**Issue by michaelarnauts** [wmalgadey/PyTado#18]
I have some strange lockups in Home Assistant recently, and this might be caused by SyncWorker starvation. The last log message I have in my logs is always a GET to Tado.

Looking at the library, it seems that there are no timeouts specified here: https://github.com/wmalgadey/PyTado/blob/master/PyTado/interface.py#L51

**Comment by michaelarnauts** [comment]
Also, it might be a good idea to move to `requests` instead of `urllib`.

**Comment by wmalgadey** [comment]
I will take a look into this this week

**Comment by michaelarnauts** [comment]
@wmalgadey any progress, or can I help with that?

**Comment by wmalgadey** [comment]
@michaelarnauts sorry for my delay! work got way too busy lately. If you have some time to spare, your help would be kindly appreciate
