### ISSUE TITLE
Implement fanspeed for AC units

### ISSUE THREAD

**Issue by michaelarnauts** [wmalgadey/PyTado#19]
AC units need a `fanSpeed` parameter that is passed.

More information here: https://github.com/home-assistant/home-assistant/issues/30020

A fork with some changes related to this is here: https://github.com/dgaust/PyTadoAC

**Comment by wmalgadey** [comment]
@michaelarnauts  @dgaust s implementation would have been a good fit, but sadly he created a new interface for ac devices!? His work is still of value.

**Comment by michaelarnauts** [comment]
Indeed. You can't just merge his changes in, but he did make some useful changes.

**Comment by dgaust** [comment]
I kind of hacked that together to see if I could get AC working in Home Assistant.

I wouldn't consider it robust at all, and ideally you'd like to be able to support setting the Fan Speed. 

Unfortunately I now longer use Tado, but I believe there's a flag in the device capabilities about whether Fan Speed is supported that you would need to check first.

Not all AC devices support Fan Speed and if you try to send it to those ones it will sort of out.

**Comment by bdraco** [comment]
I had to modify the PyTadoAC version to work with imperial units (https://github.com/bdraco/PyTadoAC) but its working well for me with the smart ac 3

**Comment by wmalgadey** [comment]
@bdraco I would like to integrate the changes in this lib, but not this week. I hope I will find time to do it asap.

**Comment by bdraco** [comment]
> @bdraco I would like to integrate the changes in this lib, but not this week. I hope I will find time to do it asap.

Excellent! I also had to change the tado integration to support imperial units in case its useful.
https://github.com/bdraco/tado

**Comment by michaelarnauts** [comment]
@bdraco doesn't it work with farenheit otherwise? I've tried to set home assistant to imperial, and everything seemed to be converted fine. Tado provides temps in both units, I just take celcius and let home assistant do the conversion.

**Comment by bdraco** [comment]
> @bdraco doesn't it work with farenheit otherwise? I've tried to set home assistant to imperial, and everything seemed to be converted fine. Tado provides temps in both units, I just take celcius and let home assistant do the conversion.

I was getting some wild numbers like it was 169 degrees in the bedroom :)

**Comment by michaelarnauts** [comment]
> > @bdraco doesn't it work with farenheit otherwise? I've tried to set home assistant to imperial, and everything seemed to be converted fine. Tado provides temps in both units, I just take celcius and let home assistant do the conversion.
> 
> I was getting some wild numbers like it was 169 degrees in the bedroom :)

For celcius, that's quite hot :) I guess for farenheit also :p I will take a look later what happens when I set the units to imperial.

**Comment by bdraco** [comment]
> > > @bdraco doesn't it work with farenheit otherwise? I've tried to set home assistant to imperial, and everything seemed to be converted fine. Tado provides temps in both units, I just take celcius and let home assistant do the conversion.
> > 
> > 
> > I was getting some wild numbers like it was 169 degrees in the bedroom :)
> 
> For celcius, that's quite hot :) I guess for farenheit also :p I will take a look later what happens when I set the units to imperial.

@michaelarnauts Were you able to replicate this issue?  I'm also happy to share one of my tado logins if its helpful (email: nick [A_T] koston [D-O-T] org)

**Comment by arttwentyfourseven** [comment]
Hi guys, I originally raised issue  30020. I have 2 Tado AC's. Happy to assist with testing, but as I'm in Australia there may be some delays due to the time difference.
