### ISSUE TITLE
tado° API credentials

### ISSUE THREAD

**Issue by Lammerink** [wmalgadey/PyTado#2]
Hi,

I just got an email from Tado that they are changing their API. 

Here is the email 

>Stefan Gaß (tado° Help Center)
>30 jun. 13:56 CEST
>
>Hello,
>
>we have noticed that you are using tado° API. Even though it is not officially supported by us yet, we wanted to inform you about some upcoming breaking changes.
>
>As you might already know, our APIs are authenticated by OAuth 2. We have recently migrated our own apps to new client credentials which uses client secret and we plan to discontinue the old credentials during next week.
>
>Please make sure you migrate your API usages to this client credentials:
>
>Client ID: public-api-preview
>Client Secret: 4HJGRffVR8xb3XdEUQpjgZ1VplJi6Xgw
>
>Also feel free to share these credentials with other developers. That way we will be able to easily distinguish our own apps from third party developers and make sure that the official public API will suit your needs.
>
>Best regards,
>Michal
>Head of Server Development
>

Does this affect the PyTado implementation?

Cheers,
Ruben

**Comment by wmalgadey** [comment]
I got the same email and changed the code.
