### ISSUE TITLE
Not understanding what is "data" in "TadoZone"

### ISSUE THREAD

**Issue by alessandro-massarenti** [wmalgadey/PyTado#40]
I'm not understanding what is "data" in "TadoZone".

How should I initialize the class?

For sure i'm a noob but i'm in need of a bit more documentation

Thank you in advance for every tipe of reply

**Comment by wmalgadey** [comment]
HI @alessandro-massarenti I don't see any data in TadoZone!?

**Comment by north3221** [comment]
@alessandro-massarenti I think you are just looking at this wrong, you don't import that TadoZone class, that's just a class for structuring the returned data from the api for the zone

instead use the ```from PyTado.interface import Tado``` as per the read me, that in turn will us the TadoZone class

**Comment by alessandro-massarenti** [comment]
> @alessandro-massarenti I think you are just looking at this wrong, you don't import that TadoZone class, that's just a class for structuring the returned data from the api for the zone
> 
> instead use the ```from PyTado.interface import Tado``` as per the read me, that in turn will us the TadoZone class

Yes, i saw that, my bad.

I felt it wrong probably because I'm not used to that python semantic.

I'm quite sorry about this wasted time.
And thanks for the clarification. 👍🏻👍🏻🙂🙂
