### ISSUE TITLE
IDEA: Add Gas usage

### ISSUE THREAD

**Issue by niro1987** [wmalgadey/PyTado#59]
Is it be possible to add gas meter usage via the API? That would be a nice feature to automatically add gas usage when combined with DSMR / Home Assistant.

**Comment by diamondo25** [comment]
I was actually looking into this, and the call to the Tado backend is as follows:
```
POST https://energy-insights.tado.com/api/homes/1234/meterReadings
{"date":"2023-03-07","reading":1584}
```

And the response is
```json
{"id":"xxxx-f16b-4ef7-be0e-fef47cb061c0","homeId":1234,"date":"2023-03-07","reading":1584}
```

To get the current readings:

```
GET https://energy-insights.tado.com/api/homes/1234/meterReadings
```

```json
{"readings":[{"id":"xxxx-f16b-4ef7-be0e-fef47cb061c0","homeId":1234,"reading":1584,"date":"2023-03-07"}]}
```

Maybe this can be easily be implemented to eventually get this into Home Assistant as a Service. Note that there's currently no "home" device of Tado, so maybe you'd want to either add that too, or bind it onto the Internet Bridge

**Comment by Coffee2CodeNL** [comment]
Let's add this. It seems useful.
