### ISSUE TITLE
PyTado returns debug log, even if debug=False

### ISSUE THREAD

**Issue by bjclopes** [wmalgadey/PyTado#67]
Hello there,

I'm sorry if this is not the right way of reaching out about this issue.
PyTado returns debug log, even if debug=False in Tado(username, password, http_session, debug)

Thanks very much for any help.

**Comment by saschabrockel** [comment]
Same here. I tried literally everything. Even overriding logger.

**Comment by tjorim** [comment]
You mean http logging? You can check if it's fixed on the masted branch: https://github.com/wmalgadey/PyTado/pull/63

**Comment by erwindouna** [comment]
@wmalgadey can you please release this python-tado on PyPi? Else there's no reason for Home Assistant to get this sourced.
Many thanks!

**Comment by wmalgadey** [comment]
Done

**Comment by erwindouna** [comment]
> Done

Thanks!
