### ISSUE TITLE
New version on PyPi broken

### ISSUE THREAD

**Issue by kloknibor** [wmalgadey/PyTado#7]
I was trying to install version 0.2.6 from PyPi only to find out  the internal package on PyPi is incorrect and the latest version that is correct is 0.2.3 .

Is it possible to upload a correct archive to PyPi for 0.2.6? Or is it because it's still labelled alpha? And when would it become the stable version?

Thanks! (Also thanks for maintaining this :)!)

**Comment by wmalgadey** [comment]
fixed in 0.2.7 on pypi
