### ISSUE TITLE
Q: Set mode 'until next automatic change'

### ISSUE THREAD

**Issue by SamJongenelen** [wmalgadey/PyTado#8]
Hey,

I can set operation mode succesfully in my V3. Awesome!
Now i would like to add a param 'how long' the mode should be set.
Any tips?

**Comment by mattthewclayton** [comment]
I appreciate this is quite a late response to this question but I have just found myself needing to do this. The following worked for me:

`t.setZoneOverlay(zone=1, overlayMode="TADO_MODE",  setTemp=22)`

The magic is "TADO_MODE" instead of "MANUAL".

**Comment by wmalgadey** [comment]
@SamJongenelen does that answer your question? It is currently not possible with our implementation to change the time, a change should be active.

**Comment by SamJongenelen** [comment]
Ah yes it answers my question yes, thank you
