### ISSUE TITLE
BUG: Temperature setting from HA not propagated to Tado since last update

### ISSUE THREAD

**Issue by derolli1976** [wmalgadey/PyTado#88]
Please refer to this issue in HA core:
https://github.com/home-assistant/core/issues/132408

Summary:
The discussion revolves around an issue with the tado integration in Home Assistant Core version 2024.12.0. Users report that they are unable to control their tado thermostats via Home Assistant after updating to this version. The problem does not generate any errors, but the target temperature is not set, and the attempt to change it does not appear in the logbook. However, changing HVAC modes and setting the temperature via the tado app still works, and the new target temperature is reflected in Home Assistant.

Several users confirm experiencing the same issue, noting that it affects older tado devices but not the newer Tado X devices. Some users have reverted to the previous version, 2024.11.3, where the functionality works as expected. There are suggestions to enable debug logging to gather more information, but no definitive solution has been found yet. The discussion includes various comments from users and contributors trying to diagnose and resolve the issue.

Maybe this change is a starting point for further investigation. In the issue above, users are saying, that setting a time for the temperature change works, what would correspond to the way the "termination" is being set.

https://github.com/wmalgadey/PyTado/compare/0.17.6...0.17.7?diff=split&w=#diff-15026f10a7c92270f8625a91f0ea320d5ea0abb601f89cc409a6495e0b89bb8aR615

**Comment by wmalgadey** [comment]
I will revert the current X integration and extract into separat code, so it cannot interfere with the already working implementation!

**Comment by wmalgadey** [comment]
@derolli1976 I made a release 0.18.0, but I am not able to test it actually. Do you have an idea how to test it?

**Comment by wmalgadey** [comment]
0.18.1 added some code coverage through tests and fixed 2 bugs

**Comment by wmalgadey** [comment]
0.18.2 added tests to http class and fixed an error with login

**Comment by wmalgadey** [comment]
latest error with 0.18.3 reported by @danfulton72
```
2024-12-19 13:34:14.571 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liverpool for tado
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 84, in async_setup_entry
    await hass.async_add_executor_job(tadoconnector.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 184, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/tado_connector.py", line 81, in update
    self.update_zones()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/tado/tado_connector.py", line 183, in update_zones
    self.update_zone(int(zone))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tado/tado_connector.py", line 189, in update_zone
    data = self.tado.get_zone_state(zone_id)
  File "/usr/local/lib/python3.13/site-packages/PyTado/interface/api/my_tado.py", line 106, in get_zone_state
    return TadoZone.from_data(zone, self.get_state(zone))
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/PyTado/zone/my_zone.py", line 259, in from_data
    return cls(zone_id=zone_id, **kwargs)
TypeError: TadoZone.__init__() got an unexpected keyword argument 'default_overlay_termination_type'. Did you mean 'overlay_termination_type'?
```

**Comment by wmalgadey** [comment]
Best would be to get the json response from 

* `zones/{zone}/state`
* `zones/{zone:d}/defaultOverlay`

I have only access to TadoX API now!

**Comment by danfulton72** [comment]
What's the best way of getting them?

**Comment by wmalgadey** [comment]
- Access my.tado.com from browser.
- Open Developer Tools and open Tab "Network"
- Open a room
- Search in Network-Tab for "state" and "defaultOverlay"
- Click on one request and you will see some more tabs like "Response"

<img width="605" alt="image" src="https://github.com/user-attachments/assets/3cb03263-17ca-409e-80af-6b0238759359" />

**Comment by wmalgadey** [comment]
I will work on it later today, because I have to leave now!

**Comment by danfulton72** [comment]
Hmm, I don't see a rooms?

I've done a journey, access my.tado.com, select a room and change the temperature - recorded the network comms, will send over the HAR file for you to see.

**Comment by wmalgadey** [comment]
Just let me know, when you are ready! I did some testing with tadox devices/api and I try to create a dummy test for your error as long as I do not have any valid test data.

**Comment by danfulton72** [comment]
I've emailed over the .har file - hopefully you can see what you need there.

Happy to do anymore investigating / log gathering as needed, thanks.

**Comment by danfulton72** [comment]
Initial impressions are good, loaded the component, and have set the temperature in one room successfully.

Will continue to use today, and feedback later on how it's going 👍 

Thanks for all your work on this 🎉

**Comment by wmalgadey** [comment]
@danfulton72 can you explain what you did to test it in your homeassistant installation? I will try to test the Tado X implementation then 🗡️

**Comment by danfulton72** [comment]
Sure, I updated

/usr/src/homeassistant/homeassistant/components/tado/manifest.json

and 

/usr/src/homeassistant/requirements_all.txt

in my docker container for Core 2024.12.0

to have a requirement of python-tado==0.18.4

Then enabled debug logs for tado component restarted home assistant container, watched the logs like a hawk for any errors (none occured).

Once HA had finished, I checked changing temperature from frontend and via a script for multiple rooms, I also checked the device tracker for tado was reporting correctly.

All seems in order.

If you can think of any other tests / validations let me know 👍

**Comment by danfulton72** [comment]
And now replicated on 2024.12.5 :)

**Comment by wmalgadey** [comment]
For reference: https://github.com/home-assistant/core/issues/132406

**Comment by danfulton72** [comment]
Still working without issue for me, I'd say good to go 👍

**Comment by wmalgadey** [comment]
then let's close this issue and maybe @erwindouna can add this version back to home assistant? For Tado X we may join forces in 2026 ;)

**Comment by erwindouna** [comment]
> then let's close this issue and maybe @erwindouna can add this version back to home assistant? For Tado X we may join forces in 2026 ;)

Let's make that 2025. ;)
